version: 2
jobs:
  build:
    working_directory: ~/jsarenik/spf-tools
    parallelism: 1
    shell: /bin/sh --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: alpine
      command: /sbin/init
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run: apk --no-progress update
    - run: apk --no-progress upgrade
    - run: apk --no-progress add diffutils coreutils sed grep
    - run: apk --no-progress add bash mksh dash loksh mksh
    - run: sh -ex misc/ci-setup.sh
    - run: sh -ex misc/ci-runtest.sh
    - store_test_results:
        path: /tmp/circleci-test-results
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
